--1. Write a SQL query to find all the orders issued by the salesman 'Paul Adam'.
SELECT s.name AS salesman_name, o.*
FROM orders o
JOIN salesman s 
ON o.salesman_id = s.salesman_id
WHERE o.salesman_id = (
    SELECT salesman_id
    FROM salesman 
    WHERE name = 'Paul Adam'
)
--2. Write a SQL query to find all orders generated by London-based salespeople. Return ord_no, purch_amt, ord_date, customer_id, salesman_id.
SELECT
		order_no,
		purch_amt,
		order_date, 
		customer_id, 
		salesman_id
FROM orders1 
WHERE salesman_id IN (
    SELECT salesman_id
    FROM salesman 
    WHERE city = 'London'
)
--3. Write a SQL query to find all orders generated by the salespeople who may work for customers whose id is 3007.
SELECT *
FROM orders
WHERE customer_id IN (
		SELECT   customer_id
        FROM salesman
        WHERE customer_id = 3007
)--Bundan emin deyilem duzdur ya yox

--4. Write a SQL query to find the order values greater than the average order value of 10th October 2012
SELECT *
FROM orders
WHERE purch_amt >(
	SELECT AVG(purch_amt)
	FROM orders
	WHERE order_date = '2016-10-10'
)
--5. Write a SQL query to find all the orders generated in New York city.
SELECT s.city, o.*
FROM orders o
JOIN salesman s ON o.salesman_id = s.salesman_id
WHERE o.salesman_id IN (
    SELECT salesman_id
    FROM salesman
    WHERE city = 'New York'
)

--6. Write a SQL query to determine the commission of the salespeople in Paris.
SELECT *
FROM salesman
WHERE salesman_id IN(
		SELECT salesman_id 
		FROM orders)
AND city = 'Paris' --bundanda emin deyilem
--7. Write a query to display all the customers whose ID is 3001 below the salesperson ID of Mc Lyon.
SELECT * from customersWHERE customer_id <(		select salesman_id  from salesman where name ='Mc Lyon')AND customer_id = 3001--8.  Write a SQL query to count the number of customers with grades above the average in New York City.
SELECT  COUNT(*) as [Count of Customers]
FROM customers
WHERE grade <(
		SELECT AVG(grade)
		FROM customers
		WHERE city = 'New York'
)
--9. Write a SQL query to find those salespeople who earned the maximum commission.SELECT *FROM salesmanWHERE comission=(		SELECT MAX(comission)		FROM salesman) --10. Write SQL query to find the customers who placed orders on 17th August 2016.
SELECT *FROM customersWHERE customer_id IN (		SELECT customer_id		FROM orders1		WHERE order_date = '2016-08-17')